services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Порт для Next.js
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://server:9375 # URL сервера для клиента

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "9375:9375" # Порт для Express сервера
    depends_on:
      - postgres # Зависимость от PostgreSQL
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=VOLTECH
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root

  postgres:
    container_name: postgres_voltech
    image: postgres:12
    env_file:
      - ./server/.env.prod
    entrypoint:
      - /bin/sh
      - -c
      - "export PGDATA=/var/lib/postgresql/data && exec docker-entrypoint.sh postgres"
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
