# Используем Node.js базовый образ
FROM node:18-alpine

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем только файлы с зависимостями (для кеширования слоев)
COPY package.json yarn.lock ./

# Устанавливаем зависимости
RUN yarn install

# Копируем остальные файлы проекта в контейнер
COPY . .

# Компилируем TypeScript в JavaScript
RUN yarn build

# Указываем команду для запуска сервера
CMD ["yarn", "start"]
